### ISSUE TITLE
Thumbnails do not work in mpv.net

### ISSUE THREAD

**Issue by sitiom** [datasone/MPVMediaControl#12]
Thumbnails do not work in [mpv.net](https://github.com/mpvnet-player/mpv.net). Can you investigate this? See https://github.com/mpvnet-player/mpv.net/issues/523

**Comment by datasone** [comment]
Here is a detailed description about the issues.
1. Consistency problem, the problem is reproducible on the published build, while disappeared on new builds (when I tried to debug it). And all new builds don't have this problem anymore. I'm not sure why but as my VS has been upgraded many times, it seems like a C# compiler issue in specific versions. So if you are still facing this kind of issues, feel free to reopen this or draft a new issue report.
2. Snapshot problem, it seems when getting snapshot image from file, Windows has very strict demand on path format. MPV.Net adds `\` after the expanded `~~/` path, makes the shot path like `C:\Users\xxx\AppData\Roaming\mpv.net\\12345.jpg`. The double backslash in path makes Windows refuses to read the file, so a workaround is added.

Both issues are now fixed in [0.2.0](../releases/0.2.0).
